kind:  ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  servers.conf: |-
    server {
      listen      80;
      server_name orders.oneclicksandwich.com;

      location / {
        proxy_pass http://10.127.244.173:15421;
      }
    }
