kind:  ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  servers.conf: |-
    server {
      listen      80;
      server_name api.oneclicksandwich.com;

      location / {
        proxy_pass http://ocs-api.default.svc.cluster.local:30379;
      }
    }
    server {
      listen      80;
      server_name moneypenny.tobysullivan.net;

      location / {
        proxy_pass http://moneypenny-service.default.svc.cluster.local:42578;
      }
    }
    server {
      listen      80;
      server_name event-store.tobysullivan.net;

      location / {
        proxy_pass http://event-store-service.default.svc.cluster.local:25583;
      }
    }
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: config
          configMap:
            name: nginx-config
            items:
            - key: servers.conf
              path: servers.conf
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d
